INSERT INTO DDU.T_DDU_PARTICIPANT
(
    CREATED_BY,
    UPDATED_BY,
    DDU_PARTICIPANT_NAME,
    DDU_PARTICIPANT_NAME_ALIAS,
    STATUS_CODE,
    SPEC_VERSION,
    DDU_PARTICIPANT_TYPE,
    LOCAL_QUEUE,
    REMOTE_QUEUE,
    RECEIVE_ACKNOWLEDGEMENT,
    SEND_HEARTBEAT
)
SELECT
    'DBA',
    'svc_dduso',
    'US Bank',
    S.FUNDING_AGENT_IDENTIFIER,
    1,
    '1.0',
    'FA',
    '{ "name":"' || S.FUNDING_AGENT_IDENTIFIER || '", "site1":["DDU.FA.USBANK.MQ1.RESPONSE.TO.DDU.MQ1"], "site2":["DDU.FA.USBANK.MQ1.RESPONSE.TO.DDU.MQ2"] }',
    '{ "name":"' || S.FUNDING_AGENT_IDENTIFIER || '", "site1":["FA.DDU.USBANK.MQ1.FROM.DDU.MQ1"], "site2":["FA.DDU.USBANK.MQ1.FROM.DDU.MQ2"] }',
    0,
    0
FROM
(
    SELECT DISTINCT FUNDING_AGENT_IDENTIFIER
    FROM DDU.DDU_FUNDING_AGENT_PARTICIPANTS
    WHERE FUNDING_AGENT_IDENTIFIER IS NOT NULL
      AND TRIM(FUNDING_AGENT_IDENTIFIER) <> ''
) S
WHERE NOT EXISTS
(
    SELECT 1
    FROM DDU.T_DDU_PARTICIPANT T
    WHERE T.DDU_PARTICIPANT_NAME_ALIAS = S.FUNDING_AGENT_IDENTIFIER
);


^.*,\s*(?!')[^,\r\n]+.*$
,\s*(?!')[^,\r\n]+
